update googletest version to 1.11.0
bab2min/Kiwi pull request #35
Opened 2021-08-29 14:15 UTC by emiatej9

fixed #34 

existing submodule googletest v1.8.x caused cmake deprecation warning, 
I updated googletest version to 1.11.0.

2021-08-29 15:49 UTC, bab2min commented
@emiatej9 
Centos5 빌드가 실패하는데, 확인해보니 centos5에 포함된 g++ 4.8이 c++11을 완벽하게 지원하지 못해서 발생하는 문제네요.
gtest 1.8.x가 pre-c++11 컴파일러를 지원하는 마지막 버전이라고 하는걸 보니 그 이후 버전부터는 Centos5에서 계속 실패할걸로 보입니다.

Centos5를 테스트에 넣은건 오래된 레거시 환경에서도 작동이 잘되도록 보장하고 싶었기 때문인데요, gtest 최신 버전이 발목을 잡는 문제가 있군요. 어떻게 해결하는게 좋을지 좀 고민해봐야할거 같아요~

1. 테스트 환경에서 Centos5를 빼고 6이나 7로 대체
2. gtest는 1.8.x로 유지하되 patch를 붙여 cmake deprecation warning을 제거
3. gtest를 최신 버전으로 업데이트하되 Centos5 빌드시에만 gtest 1.8.x를 사용하도록 빌드 workflow 수정

2021-08-30 08:39 UTC, emiatej9 commented
그렇다면 CentOS 5에서는 빌드에서 사용하는 cmake 버전과 googletest 버전을 둘 다 낮춰서 테스트를 구성하는 방법이 있을까요? 제가 git workflow 는 잘 몰라서 감이 없네요.

만약  CentOS 5만 cmake 버전과 googletest 버전을 낮춰서 구성할 수 있다면, 이들 (구)버전까지 커버할 수 있도록 CMakeLists.txt 파일이나    googletest 관련 부분이 분기를 나누어주어야 할 수도 있겠네요.

2021-08-30 12:27 UTC, bab2min commented
@emiatej9 
네, 저도 고민해봤는데 Centos5에서만 버전을 낮추고 나머지는 최신 버전을 유지하는게 제일 좋아보이네요. 일단 third_party/googletest는 지금처럼 최신 버전으로 업데이트한채로 두고, Centos5에서만 `tags/release-1.8.1`로 checkout해주면 될것 같네요. (https://github.com/google/googletest/tree/release-1.8.1 )

https://github.com/bab2min/Kiwi/blob/099651822d99fa980a7b38413c95bfec11f93783/.github/workflows/centos5.yml#L14-L23

이 부분이 Centos5 workflow인데 Configure Build 전에 step을 하나 추가해서 googletest 레포를 `tags/release-1.8.1`로 checkout해주도록 수정가능하신가요?

2021-08-30 12:29 UTC, emiatej9 commented
네, 수정해서 커밋 해보겠습니다.

2021-08-31 15:27 UTC, bab2min requested changes
잘해주셨는데요 마지막에 cd가 빠졌네요. 해당부분만 수정해주시면 문제없이 빌드될거 같습니다!

2021-08-31 15:27 UTC, bab2min commented on .github/workflows/centos5.yml
> +      run: cd third_party/googletest && git checkout v1.8.x && ../..
`../..` 앞에 cd가 빠졌네요~

2021-09-02 04:16 UTC, merged

2021-09-02 04:17 UTC, bab2min commented
@emiatej9 
테스트 잘 통과해서 머지했습니다~ 기여에 감사드립니다.